spring:
  profiles:
    active: dev
---
server:
  port: 3333
spring:
  application:
    name: DEV  #开发环境
  profiles: dev
---
server:
  port: 4444
spring:
  application:
    name: TEST  #测试环境
  profiles: test
